#!/bin/env bash

#connect to web-01, 2 or lb

SERVER="$1"

echo $SERVER

if [ $# -ne 1 ];
then
	echo "Usage: ./conn <server: web1 | web2 | lb1 | ...>"
fi


case $SERVER in
	"web1")
		IP="54.157.188.132";;

	"web2")
		IP="54.237.11.189";;
	
	"lb1")
		IP="54.173.68.142";;

	*)
		echo "---No matches---"
		exit 1
		;;
		

esac


ssh -i ~/.ssh/school ubuntu@$IP
:'
	if [ $# -lt 3 ];
	then
		        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		elif [ $# -lt 4 ]; then
			        scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
				exit
	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

	fi

'

